### ISSUE TITLE
Add a devtools docker-compose service for the CI commands

### ISSUE THREAD

**Issue by sebas5384** [TallerWebSolutions/drupal-enterprise-boilerplate#39]
this is needed in order to avoid unnecessary download of mysql and solr imagens for the build.

example
```
 devtools:
    extends:
      service: meta
    image: devtools
    build:
      context: ./docker/
      args:
        USER_ID: '$USER_ID'
        GROUP_ID: '$GROUP_ID'
    hostname: devtools
    volumes:
      - $PWD:/taller/app
```
